// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAm3VKciEA0VwhEDYuwMewNJU9WZAOZFas',
    appId: '1:936483393668:web:86d5dc75408364c35eb2d1',
    messagingSenderId: '936483393668',
    projectId: 'twofmetelung',
    authDomain: 'twofmetelung.firebaseapp.com',
    storageBucket: 'twofmetelung.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4fUVRI71mdg-6eudlsQyF9P6H1TmiXA8',
    appId: '1:936483393668:android:fa9927cfe79319e15eb2d1',
    messagingSenderId: '936483393668',
    projectId: 'twofmetelung',
    storageBucket: 'twofmetelung.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnFYmBLDDNwgaa9290Gw9hmQKdVuzZqEo',
    appId: '1:936483393668:ios:a1b83f5a000a5ef35eb2d1',
    messagingSenderId: '936483393668',
    projectId: 'twofmetelung',
    storageBucket: 'twofmetelung.firebasestorage.app',
    iosBundleId: 'com.masterung.twofmetelproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnFYmBLDDNwgaa9290Gw9hmQKdVuzZqEo',
    appId: '1:936483393668:ios:a1b83f5a000a5ef35eb2d1',
    messagingSenderId: '936483393668',
    projectId: 'twofmetelung',
    storageBucket: 'twofmetelung.firebasestorage.app',
    iosBundleId: 'com.masterung.twofmetelproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAm3VKciEA0VwhEDYuwMewNJU9WZAOZFas',
    appId: '1:936483393668:web:6841c53eeabb80915eb2d1',
    messagingSenderId: '936483393668',
    projectId: 'twofmetelung',
    authDomain: 'twofmetelung.firebaseapp.com',
    storageBucket: 'twofmetelung.firebasestorage.app',
  );
}
